name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.1.0
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql
dependencies:
  meta: ^1.7.0
  path: ^1.8.0
  gql: ^0.13.1-alpha+1635885531641
  gql_exec: ^0.3.2-alpha+1635885531651
  gql_link: ^0.4.2-alpha+1635885531659
  gql_http_link: ^0.4.2-alpha+1635885531688
  gql_transform_link: ^0.2.2-alpha+1635885531679
  gql_error_link: ^0.2.2-alpha+1635885531699
  gql_dedupe_link: ^2.0.2-alpha+1635885531760
  hive: ^2.0.4
  normalize: ^0.5.5
  http: ^0.13.4
  collection: ^1.15.0
  web_socket_channel: ^2.1.0
  stream_channel: ^2.1.0
  rxdart: ^0.27.2
  uuid: ^3.0.5
dev_dependencies:
  async: ^2.8.2
  flutter_lints: 1.0.4
  mockito: ^5.0.16
  test: ^1.19.3
  http_parser: ^4.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'
