name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.0.0
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter
publish_to: none
dependencies:
  graphql: # 5.0.0
    path: ../graphql
  gql_exec: ^0.3.2-alpha+1635885531651
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path_provider: ^2.0.6
  path: ^1.8.0
  connectivity_plus: ^2.0.2
  hive: ^2.0.4
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  mockito: ^5.0.0
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  http: ^0.13.0
environment:
  sdk: '>=2.12.0 <3.0.0'
